[package]
name = "baeum"
version = "0.0.1"
authors = ["Choongwoo Han <cwhan.tunz@gmail.com>"]
build = "build.rs"

[dependencies]
clap = "2.19"
log = "0.3.6"
env_logger = "0.3.5"
rand = "0.3"
memmap = "0.5.0"
byteorder = "1.0.0"
rustful = "0.9"

[build-dependencies]
gcc = "0.3"
